### PR TITLE
change about to team. add desctiption for front page and logo.

### PR DESCRIPTION
**Pull request by christhechris**

### CODE REVIEW

**Comment by christhechris** [comment]
some updated text and formatting. something that changed is making the header menu disappear. tried a few things, not sure why, perhaps you can see?

**Comment by christhechris** [comment]
pages temp pointed to this branch btw.

**Comment by YiweiMao** [comment]
I think the config.yml file changed the header menu. Updated the wording a bit. content looks good now.

**Comment by christhechris** [comment]
I thought I had tried with and with out those changes and it still wasn’t showing up. Maybe it will work now.

**Comment by christhechris** [comment]
Still not showing. Maybe it actually needs the about heading in md file?

**Review by christhechris — COMMENTED** [review]
The readme went back to the uninformative auto gen.

**Comment by YiweiMao** [comment]
Yeah, just trying some things to understand what's going on.

**Comment by christhechris** [comment]
> Still not showing. Maybe it actually needs the about heading in md file?

I think it is this.

**Comment by YiweiMao** [comment]
Okay, fixed now. 
`index.md` cannot start with a heading otherwise, it removes the side menu.
`about.md` must start with a heading (and the "About" is renamed to this heading) otherwise it disappears.

**Comment by christhechris** [comment]
Confusing! nice work!

**Comment by christhechris** [comment]
Any idea how to change the footer? The repeated OpenHSI’s look odd imo.

**Comment by christhechris** [comment]
Last comment for night from me 😉 ...A theme with a spot for logo would probably be nice.

**Comment by YiweiMao** [comment]
Okay, that took a lot of experimenting but the new theme (minimal, as opposed to the original minima) is a go. The annoying footer is gone, hurrah!
There was a space for the logo but we lose the header link to the About page so I added this back in, albeit an adhoc way.

**Review by YiweiMao — APPROVED** [review]
looking good now

**Pull request merged**
